name: "Deploy MultiDocker"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nicram97/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nicram97/react-test npm test

      - run: docker build -t nicram97/multi-client -f ./client
      - run: docker build -t nicram97/multi-nginx -f ./nginx
      - run: docker build -t nicram97/multi-server -f ./server
      - run: docker build -t nicram97/multi-worker -f ./worker

      - run: docker push nicram97/multi-client
      - run: docker push nicram97/multi-nginx
      - run: docker push nicram97/multi-server
      - run: docker push nicram97/multi-worker